# -*- coding: utf-8 -*-
"""
Script que lee los 104 jugadores originales, actualiza sus IDs de club y fotos correctas,
y expande el archivo con más de 950 jugadores reales adicionales con clubes oficiales para superar las 1000 cartas.
"""

import os
import json
import re
from generator_core import CLUBS, NATIONS, qs_val, generate_stats_for, generate_player

# 1. Cargar base de datos actual para conservar las 104 cartas existentes (con sus escudos y caras actualizadas)
with open('pacibyts/ui/database.js', 'r', encoding='utf-8') as f:
    original_text = f.read()

# Mapeo de nombres de club a los nuevos IDs oficiales
CLUB_NAME_TO_NEW_ID = {
    "Real Madrid": 86,
    "FC Barcelona": 81,
    "Manchester City": 65,
    "Liverpool": 64,
    "Bayern München": 5,
    "Arsenal": 57,
    "Chelsea": 61,
    "Manchester United": 66,
    "Paris Saint-Germain": 524,
    "Inter": 108,
    "AC Milan": 98,
    "Atlético de Madrid": 78,
    "Bayer Leverkusen": 3,
    "Juventus": 109,
    "Borussia Dortmund": 4,
    "Tottenham Hotspur": 73,
    "Roma": 100,
    "Napoli": 113,
    "Newcastle United": 67,
    "Athletic Club": 77,
    "Real Betis": 90,
    "Sevilla": 559,
    "Real Sociedad": 92,
    "Villarreal": 94,
    "Girona": 298,
    "Atalanta": 102,
    "Lazio": 110,
    "Fulham": 63,
    "Wolverhampton": 76,
    "Everton": 62,
    "West Ham": 563,
    "Marseille": 516,
    "Monaco": 548,
    "RB Leipzig": 721,
    "Eintracht Frankfurt": 19,
    "Porto": 503,
    "Sporting CP": 1903,
    "Ajax": 678,
    "PSV": 674,
    "Feyenoord": 675,
    "Galatasaray": 610,
    "Fenerbahce": 611,
    "Como": "como",
    "River Plate": "river",
    "Boca Juniors": "boca",
    "Palmeiras": "palmeiras",
    "Inter Miami": "inter_miami",
    "Al Nassr": "al_nassr",
    "Al Hilal": "al_hilal",
    "Al Ittihad": "al_ittihad",
}

# Lista de datos masivos para las 20 mejores plantillas del mundo y ligas top:
# (nombre, nombreCompleto, media, rareza, posicion, pais, club)
PLAYERS_CATALOG = [
    # --- ICONOS ADICIONALES ---
    ("Zico", "Arthur Antunes Coimbra", 94, "icon", "MCO", "br", "FUT Icons"),
    ("Muller", "Gerd Müller", 94, "icon", "DEL", "de", "FUT Icons"),
    ("Van Basten", "Marco van Basten", 93, "icon", "DEL", "nl", "FUT Icons"),
    ("Baresi", "Franco Baresi", 93, "icon", "DFC", "it", "FUT Icons"),
    ("Puskas", "Ferenc Puskás", 94, "icon", "DEL", "hu", "FUT Icons"),
    ("Baggio", "Roberto Baggio", 93, "icon", "MCO", "it", "FUT Icons"),
    ("Eusebio", "Eusébio da Silva Ferreira", 93, "icon", "DEL", "pt"),
    ("Carlos Alberto", "Carlos Alberto Torres", 93, "icon", "LD", "br"),
    ("Cafu", "Marcos Evangelista de Morais", 93, "icon", "LD", "br"),
    ("Roberto Carlos", "Roberto Carlos da Silva", 91, "icon", "LI", "br"),
    ("Casillas", "Iker Casillas Fernández", 92, "icon", "POR", "es"),
    ("Buffon", "Gianluigi Buffon", 93, "icon", "POR", "it"),
    ("Xavi", "Xavier Hernández Creus", 93, "icon", "MC", "es"),
    ("Iniesta Icon", "Andrés Iniesta Luján", 94, "icon", "MC", "es"),
    ("Pirlo", "Andrea Pirlo", 92, "icon", "MC", "it"),
    ("Matthaus", "Lothar Matthäus", 93, "icon", "MC", "de"),
    ("Vieira", "Patrick Vieira", 91, "icon", "MCD", "fr"),
    ("Kaka", "Ricardo Izecson dos Santos Leite", 91, "icon", "MCO", "br"),
    ("Cantona", "Éric Daniel Pierre Cantona", 93, "icon", "DEL", "fr"),
    ("Shevchenko", "Andriy Shevchenko", 91, "icon", "DEL", "ua"),
    ("Del Piero", "Alessandro Del Piero", 92, "icon", "SD", "it"),
    ("Nedved", "Pavel Nedvěd", 91, "icon", "MI", "cz"),
    ("Bergkamp", "Dennis Bergkamp", 92, "icon", "SD", "nl"),
    ("Puyol", "Carles Puyol Saforcada", 92, "icon", "DFC", "es"),
    ("Cannavaro", "Fabio Cannavaro", 92, "icon", "DFC", "it"),
    ("Schmeichel", "Peter Schmeichel", 92, "icon", "POR", "dk"),
    ("Van der Sar", "Edwin van der Sar", 91, "icon", "POR", "nl"),
    ("Cech", "Petr Čech", 91, "icon", "POR", "cz"),
    ("Drogba", "Didier Drogba", 91, "icon", "DEL", "ci"),
    ("Torres", "Fernando Torres", 89, "icon", "DEL", "es"),
    ("Eto'o", "Samuel Eto'o Fils", 92, "icon", "DEL", "cm"),
    ("Raul", "Raúl González Blanco", 92, "icon", "DEL", "es"),
    ("Hierro", "Fernando Hierro", 90, "icon", "DFC", "es"),
    ("Koeman", "Ronald Koeman", 91, "icon", "DFC", "nl"),
    ("Blanc", "Laurent Blanc", 91, "icon", "DFC", "fr"),
    ("Desailly", "Marcel Desailly", 91, "icon", "DFC", "fr"),
    ("Ferdinand", "Rio Ferdinand", 90, "icon", "DFC", "gb-eng"),
    ("Lahm", "Philipp Lahm", 91, "icon", "LD", "de"),
    ("Zanetti", "Javier Zanetti", 92, "icon", "LD", "ar"),
    ("Scholes", "Paul Scholes", 91, "icon", "MC", "gb-eng"),
    ("Gerrard", "Steven Gerrard", 91, "icon", "MC", "gb-eng"),
    ("Lampard", "Frank Lampard", 90, "icon", "MC", "gb-eng"),
    ("Rivaldo", "Rivaldo Vítor Borba Ferreira", 92, "icon", "EI", "br"),
    ("Figo", "Luís Filipe Madeira Caeiro Figo", 92, "icon", "ED", "pt"),
    ("Best", "George Best", 93, "icon", "ED", "gb-eng"),
    ("Garrincha", "Manuel Francisco dos Santos", 94, "icon", "ED", "br"),
    ("Jairzinho", "Jair Ventura Filho", 92, "icon", "ED", "br"),
    ("Ribery", "Franck Ribéry", 90, "icon", "EI", "fr"),
    ("Robben", "Arjen Robben", 90, "icon", "ED", "nl"),

    # --- HÉROES FUT ADICIONALES ---
    ("Yaya Toure", "Gnégnéri Yaya Touré", 88, "hero", "MC", "ci", "Premier League"),
    ("Di Natale", "Antonio Di Natale", 88, "hero", "DEL", "it", "Serie A"),
    ("Morientes", "Fernando Morientes", 89, "hero", "DEL", "es", "LaLiga"),
    ("Cordoba", "Iván Ramiro Córdoba", 87, "hero", "DFC", "co", "Serie A"),
    ("Kompany", "Vincent Kompany", 89, "hero", "DFC", "be", "Premier League"),
    ("Carvalho", "Ricardo Carvalho", 88, "hero", "DFC", "pt", "Premier League"),
    ("Capdevila", "Joan Capdevila", 88, "hero", "LI", "es", "LaLiga"),
    ("Marchisio", "Claudio Marchisio", 88, "hero", "MC", "it", "Serie A"),
    ("Milito", "Diego Milito", 88, "hero", "DEL", "ar", "Serie A"),
    ("Kewell", "Harry Kewell", 87, "hero", "EI", "au", "Premier League"),
    ("Govou", "Sidney Govou", 86, "hero", "ED", "fr", "Ligue 1"),
    ("Park Ji Sung", "Park Ji-sung", 87, "hero", "MI", "kr", "Premier League"),
    ("Smolarek", "Włodzimierz Smolarek", 86, "hero", "DEL", "pl", "Bundesliga"),
    ("Kohler", "Jürgen Kohler", 89, "hero", "DFC", "de", "Bundesliga"),
    ("Tevez", "Carlos Tévez", 88, "hero", "DEL", "ar", "Premier League"),
    ("Ramires", "Ramires Santos do Nascimento", 87, "hero", "MCD", "br", "Premier League"),
    ("Futre", "Paulo Futre", 89, "hero", "EI", "pt", "Liga Portugal"),
    ("Sneijder", "Wesley Sneijder", 88, "hero", "MCO", "nl", "Serie A"),
    ("Hazard", "Eden Hazard", 89, "hero", "EI", "be", "Premier League"),
    ("Maicon", "Maicon Douglas Sisenando", 88, "hero", "LD", "br", "Serie A"),
]

# Generación masiva de jugadores organizados por clubes
CLUB_ROSTERS = {
    "Real Madrid": [
        ("Mbappe", "Kylian Mbappé", 91, "gold_rare", "DEL", "fr"),
        ("Vinicius Jr", "Vinícius José Paixão de Oliveira Júnior", 90, "gold_rare", "EI", "br"),
        ("Bellingham", "Jude Bellingham", 90, "gold_rare", "MCO", "gb-eng"),
        ("Valverde", "Federico Valverde", 88, "gold_rare", "MC", "uy"),
        ("Courtois", "Thibaut Courtois", 89, "gold_rare", "POR", "be"),
        ("Rudiger", "Antonio Rüdiger", 88, "gold_rare", "DFC", "de"),
        ("Rodrygo", "Rodrygo Silva de Goes", 86, "gold_rare", "ED", "br"),
        ("Camavinga", "Eduardo Camavinga", 84, "gold_rare", "MC", "fr"),
        ("Tchouameni", "Aurélien Tchouaméni", 85, "gold_rare", "MCD", "fr"),
        ("Modric", "Luka Modrić", 86, "gold_rare", "MC", "hr"),
        ("Carvajal", "Daniel Carvajal Ramos", 86, "gold_rare", "LD", "es"),
        ("Alaba", "David Olatukunbo Alaba", 85, "gold_rare", "DFC", "at"),
        ("Militao", "Éder Gabriel Militão", 85, "gold_rare", "DFC", "br"),
        ("Brahim Diaz", "Brahim Abdelkader Díaz", 84, "gold_rare", "MCO", "ma"),
        ("Mendy", "Ferland Mendy", 83, "gold_rare", "LI", "fr"),
        ("Arda Guler", "Arda Güler", 78, "gold_rare", "MCO", "tr"),
        ("Endrick", "Endrick Felipe Moreira de Sousa", 77, "gold_rare", "DEL", "br"),
        ("Ceballos", "Daniel Ceballos Fernández", 79, "gold_rare", "MC", "es"),
        ("Lucas Vazquez", "Lucas Vázquez Iglesias", 81, "gold_rare", "LD", "es"),
        ("Fran Garcia", "Francisco José García Torres", 78, "gold_rare", "LI", "es"),
        ("Lunin", "Andriy Lunin", 81, "gold_rare", "POR", "ua"),
        ("Vallejo", "Jesús Vallejo", 73, "silver", "DFC", "es"),
        ("Nico Paz", "Nicolás Paz Martínez", 70, "silver", "MCO", "ar"),
    ],
    "FC Barcelona": [
        ("Lewandowski", "Robert Lewandowski", 88, "gold_rare", "DEL", "pl"),
        ("Lamine Yamal", "Lamine Yamal Nasraoui Ebana", 84, "gold_rare", "ED", "es"),
        ("Raphinha", "Raphael Dias Belloli", 86, "gold_rare", "EI", "br"),
        ("Pedri", "Pedro González López", 86, "gold_rare", "MC", "es"),
        ("Gavi", "Pablo Martín Páez Gavira", 83, "gold_rare", "MC", "es"),
        ("De Jong", "Frenkie de Jong", 87, "gold_rare", "MC", "nl"),
        ("Kounde", "Jules Koundé", 85, "gold_rare", "LD", "fr"),
        ("Araujo", "Ronald Federico Araújo da Silva", 85, "gold_rare", "DFC", "uy"),
        ("Cubarsi", "Pau Cubarsí Paredes", 76, "gold_rare", "DFC", "es"),
        ("Balde", "Alejandro Balde Martínez", 81, "gold_rare", "LI", "es"),
        ("Ter Stegen", "Marc-André ter Stegen", 89, "gold_rare", "POR", "de"),
        ("Dani Olmo", "Daniel Olmo Carvajal", 84, "gold_rare", "MCO", "es"),
        ("Ferran Torres", "Ferran Torres García", 80, "gold_rare", "DEL", "es"),
        ("Fermin", "Fermín López Marín", 77, "gold_rare", "MC", "es"),
        ("Casado", "Marc Casadó Torras", 74, "silver", "MCD", "es"),
        ("Hector Fort", "Héctor Fort Carvillano", 68, "silver", "LD", "es"),
        ("Christensen", "Andreas Christensen", 82, "gold_rare", "DFC", "dk"),
        ("Inigo Martinez", "Íñigo Martínez Berridi", 81, "gold_rare", "DFC", "es"),
        ("Ansu Fati", "Anssumane Fati Vieira", 77, "gold_rare", "EI", "es"),
        ("Pau Victor", "Pau Víctor Delgado", 72, "silver", "DEL", "es"),
        ("Inaki Pena", "Ignacio Peña Sotorres", 75, "gold_rare", "POR", "es"),
        ("Pablo Torre", "Pablo Torre Carral", 73, "silver", "MCO", "es"),
    ],
    "Manchester City": [
        ("Haaland", "Erling Braut Haaland", 91, "gold_rare", "DEL", "no"),
        ("Rodri", "Rodrigo Hernández Cascante", 91, "gold_rare", "MCD", "es"),
        ("De Bruyne", "Kevin De Bruyne", 90, "gold_rare", "MC", "be"),
        ("Foden", "Phil Foden", 88, "gold_rare", "ED", "gb-eng"),
        ("Bernardo Silva", "Bernardo Mota Veiga de Carvalho e Silva", 88, "gold_rare", "MC", "pt"),
        ("Ruben Dias", "Rúben dos Santos Gato Alves Dias", 88, "gold_rare", "DFC", "pt"),
        ("Ederson", "Ederson Santana de Moraes", 88, "gold_rare", "POR", "br"),
        ("Gvardiol", "Joško Gvardiol", 85, "gold_rare", "LI", "hr"),
        ("Akanji", "Manuel Obafemi Akanji", 84, "gold_rare", "DFC", "ch"),
        ("Ake", "Nathan Benjamin Aké", 83, "gold_rare", "DFC", "nl"),
        ("Stones", "John Stones", 84, "gold_rare", "DFC", "gb-eng"),
        ("Walker", "Kyle Andrew Walker", 84, "gold_rare", "LD", "gb-eng"),
        ("Gundogan", "İlkay Gündoğan", 86, "gold_rare", "MC", "de"),
        ("Kovacic", "Mateo Kovačić", 83, "gold_rare", "MC", "hr"),
        ("Grealish", "Jack Peter Grealish", 84, "gold_rare", "EI", "gb-eng"),
        ("Doku", "Jérémy Bafour Doku", 81, "gold_rare", "EI", "be"),
        ("Savinho", "Sávio Moreira de Oliveira", 82, "gold_rare", "ED", "br"),
        ("Matheus Nunes", "Matheus Luiz Nunes", 79, "gold_rare", "MC", "pt"),
        ("Rico Lewis", "Rico Mark Lewis", 76, "gold_rare", "LD", "gb-eng"),
        ("Ortega", "Stefan Ortega Moreno", 79, "gold_rare", "POR", "de"),
        ("Bobb", "Oscar Bobb", 74, "silver", "ED", "no"),
    ],
    "Liverpool": [
        ("Salah", "Mohamed Salah Hamed Mahrous Ghaly", 89, "gold_rare", "ED", "eg"),
        ("Van Dijk", "Virgil van Dijk", 89, "gold_rare", "DFC", "nl"),
        ("Alisson", "Alisson Ramses Becker", 89, "gold_rare", "POR", "br"),
        ("Alexander-Arnold", "Trent John Alexander-Arnold", 86, "gold_rare", "LD", "gb-eng"),
        ("Mac Allister", "Alexis Mac Allister", 86, "gold_rare", "MC", "ar"),
        ("Szoboszlai", "Dominik Szoboszlai", 83, "gold_rare", "MCO", "hu"),
        ("Luis Diaz", "Luis Fernando Díaz Marulanda", 84, "gold_rare", "EI", "co"),
        ("Darwin Nunez", "Darwin Gabriel Núñez Ribeiro", 82, "gold_rare", "DEL", "uy"),
        ("Gakpo", "Cody Mathès Gakpo", 83, "gold_rare", "EI", "nl"),
        ("Diogo Jota", "Diogo José Teixeira da Silva", 84, "gold_rare", "DEL", "pt"),
        ("Robertson", "Andrew Robertson", 85, "gold_rare", "LI", "gb-eng"),
        ("Konate", "Ibrahima Konaté", 83, "gold_rare", "DFC", "fr"),
        ("Gravenberch", "Ryan Jiro Gravenberch", 83, "gold_rare", "MC", "nl"),
        ("Curtis Jones", "Curtis Julian Jones", 79, "gold_rare", "MC", "gb-eng"),
        ("Elliott", "Harvey Daniel James Elliott", 78, "gold_rare", "MCO", "gb-eng"),
        ("Endo", "Wataru Endo", 80, "gold_rare", "MCD", "jp"),
        ("Chiesa", "Federico Chiesa", 83, "gold_rare", "ED", "it"),
        ("Quansah", "Jarell Amorin Quansah", 76, "gold_rare", "DFC", "gb-eng"),
        ("Bradley", "Conor Bradley", 75, "gold_rare", "LD", "gb-eng"),
        ("Kelleher", "Caoimhín Odhrán Kelleher", 77, "gold_rare", "POR", "ie"),
        ("Tsimikas", "Konstantinos Tsimikas", 77, "gold_rare", "LI", "gr"),
        ("Bajcetic", "Stefan Bajčetić", 72, "silver", "MCD", "es"),
    ],
    "Arsenal": [
        ("Saka", "Bukayo Ayoyinka Saka", 87, "gold_rare", "ED", "gb-eng"),
        ("Odegaard", "Martin Ødegaard", 89, "gold_rare", "MCO", "no"),
        ("Saliba", "William Alain André Gabriel Saliba", 87, "gold_rare", "DFC", "fr"),
        ("Gabriel Magalhaes", "Gabriel dos Santos Magalhães", 86, "gold_rare", "DFC", "br"),
        ("Rice", "Declan Rice", 87, "gold_rare", "MCD", "gb-eng"),
        ("Havertz", "Kai Lukas Havertz", 84, "gold_rare", "DEL", "de"),
        ("Martinelli", "Gabriel Teodoro Martinelli Silva", 83, "gold_rare", "EI", "br"),
        ("Raya", "David Raya Martín", 84, "gold_rare", "POR", "es"),
        ("White", "Benjamin William White", 84, "gold_rare", "LD", "gb-eng"),
        ("Timber", "Jurriën David Norman Timber", 81, "gold_rare", "DFC", "nl"),
        ("Calafiori", "Riccardo Calafiori", 81, "gold_rare", "LI", "it"),
        ("Merino", "Mikel Merino Zazón", 84, "gold_rare", "MC", "es"),
        ("Partey", "Thomas Teye Partey", 83, "gold_rare", "MCD", "gh"),
        ("Trossard", "Leandro Trossard", 83, "gold_rare", "EI", "be"),
        ("Jesus", "Gabriel Fernando de Jesus", 82, "gold_rare", "DEL", "br"),
        ("Sterling", "Raheem Shaquille Sterling", 81, "gold_rare", "ED", "gb-eng"),
        ("Tomiyasu", "Takehiro Tomiyasu", 79, "gold_rare", "DFC", "jp"),
        ("Zinchenko", "Oleksandr Volodymyrovych Zinchenko", 79, "gold_rare", "LI", "ua"),
        ("Jorginho", "Jorge Luiz Frello Filho", 82, "gold_rare", "MC", "it"),
        ("Kiwior", "Jakub Piotr Kiwior", 77, "gold_rare", "DFC", "pl"),
        ("Nwaneri", "Ethan Chidiebere Nwaneri", 68, "silver", "MCO", "gb-eng"),
        ("Lewis-Skelly", "Myles Lewis-Skelly", 66, "silver", "MCD", "gb-eng"),
    ],
    "Bayern München": [
        ("Kane", "Harry Edward Kane", 90, "gold_rare", "DEL", "gb-eng"),
        ("Musiala", "Jamal Musiala", 87, "gold_rare", "MCO", "de"),
        ("Sane", "Leroy Aziz Sané", 85, "gold_rare", "ED", "de"),
        ("Kimmich", "Joshua Walter Kimmich", 86, "gold_rare", "MC", "de"),
        ("Neuer", "Manuel Peter Neuer", 86, "gold_rare", "POR", "de"),
        ("Upamecano", "Dayotchanculle Oswald Upamecano", 83, "gold_rare", "DFC", "fr"),
        ("Min Jae Kim", "Kim Min-jae", 84, "gold_rare", "DFC", "kr"),
        ("Davies", "Alphonso Boyle Davies", 83, "gold_rare", "LI", "ca"),
        ("Olise", "Michael Akpovie Olise", 82, "gold_rare", "ED", "fr"),
        ("Gnabry", "Serge David Gnabry", 82, "gold_rare", "EI", "de"),
        ("Coman", "Kingsley Junior Coman", 84, "gold_rare", "EI", "fr"),
        ("Palhinha", "João Pedro Gonçalves Neves Palhinha", 85, "gold_rare", "MCD", "pt"),
        ("Goretzka", "Leon Christoph Goretzka", 83, "gold_rare", "MC", "de"),
        ("Pavlovic", "Aleksandar Pavlović", 76, "gold_rare", "MC", "de"),
        ("Laimer", "Konrad Laimer", 81, "gold_rare", "MC", "at"),
        ("Guerreiro", "Raphaël Adelino José Guerreiro", 81, "gold_rare", "LI", "pt"),
        ("Boey", "Sacha Gaston Boey", 79, "gold_rare", "LD", "fr"),
        ("Dier", "Eric Jeremy Edgar Dier", 78, "gold_rare", "DFC", "gb-eng"),
        ("Ito", "Hiroki Ito", 79, "gold_rare", "DFC", "jp"),
        ("Tel", "Mathys Henri Tel", 77, "gold_rare", "DEL", "fr"),
        ("Ulreich", "Sven Ulreich", 74, "silver", "POR", "de"),
    ],
    "Paris Saint-Germain": [
        ("Dembele", "Masour Ousmane Dembélé", 86, "gold_rare", "ED", "fr"),
        ("Donnarumma", "Gianluigi Donnarumma", 89, "gold_rare", "POR", "it"),
        ("Marquinhos", "Marcos Aoás Corrêa", 87, "gold_rare", "DFC", "br"),
        ("Hakimi", "Achraf Hakimi Mouh", 85, "gold_rare", "LD", "ma"),
        ("Barcola", "Bradley Barcola", 82, "gold_rare", "EI", "fr"),
        ("Vitinha", "Vítor Machado Ferreira", 85, "gold_rare", "MC", "pt"),
        ("Zaire-Emery", "Warren Zaïre-Emery", 80, "gold_rare", "MC", "fr"),
        ("Joao Neves", "João Pedro Neves Filipe", 80, "gold_rare", "MC", "pt"),
        ("Pacho", "William Joel Pacho Tenorio", 80, "gold_rare", "DFC", "ec"),
        ("Nuno Mendes", "Nuno Alexandre Tavares Mendes", 83, "gold_rare", "LI", "pt"),
        ("Fabian Ruiz", "Fabián Ruiz Peña", 82, "gold_rare", "MC", "es"),
        ("Asensio", "Marco Asensio Willemsen", 81, "gold_rare", "ED", "es"),
        ("Kang-in Lee", "Lee Kang-in", 79, "gold_rare", "MCO", "kr"),
        ("Kolo Muani", "Randal Kolo Muani", 82, "gold_rare", "DEL", "fr"),
        ("Goncalo Ramos", "Gonçalo Matias Ramos", 81, "gold_rare", "DEL", "pt"),
        ("Lucas Hernandez", "Lucas François Bernard Hernández", 83, "gold_rare", "DFC", "fr"),
        ("Beraldo", "Lucas Lopes Beraldo", 77, "gold_rare", "DFC", "br"),
        ("Skriniar", "Milan Škriniar", 82, "gold_rare", "DFC", "sk"),
        ("Safonov", "Matvey Safonov", 78, "gold_rare", "POR", "ru"),
        ("Mayulu", "Senny Mayulu", 67, "silver", "MC", "fr"),
    ],
    "Inter": [
        ("Lautaro Martinez", "Lautaro Javier Martínez", 89, "gold_rare", "DEL", "ar"),
        ("Barella", "Nicolò Barella", 87, "gold_rare", "MC", "it"),
        ("Bastoni", "Alessandro Bastoni", 87, "gold_rare", "DFC", "it"),
        ("Calhanoglu", "Hakan Çalhanoğlu", 86, "gold_rare", "MC", "tr"),
        ("Dimarco", "Federico Dimarco", 84, "gold_rare", "LI", "it"),
        ("Thuram", "Marcus Lilian Thuram-Ulien", 83, "gold_rare", "DEL", "fr"),
        ("Sommer", "Yann Sommer", 87, "gold_rare", "POR", "ch"),
        ("Pavard", "Benjamin Jacques Marcel Pavard", 84, "gold_rare", "DFC", "fr"),
        ("Acerbi", "Francesco Acerbi", 84, "gold_rare", "DFC", "it"),
        ("De Vrij", "Stefan de Vrij", 83, "gold_rare", "DFC", "nl"),
        ("Mkhitaryan", "Henrikh Hamleti Mkhitaryan", 83, "gold_rare", "MC", "am"),
        ("Dumfries", "Denzel Justus Morris Dumfries", 82, "gold_rare", "LD", "nl"),
        ("Frattesi", "Davide Frattesi", 81, "gold_rare", "MC", "it"),
        ("Zielinski", "Piotr Sebastian Zieliński", 81, "gold_rare", "MC", "pl"),
        ("Taremi", "Mehdi Taremi", 80, "gold_rare", "DEL", "ir"),
        ("Darmian", "Matteo Darmian", 81, "gold_rare", "LD", "it"),
        ("Carlos Augusto", "Carlos Augusto Zopolato Neves", 79, "gold_rare", "LI", "br"),
        ("Asllani", "Kristjan Asllani", 75, "gold_rare", "MCD", "al"),
        ("Bisseck", "Yann Aurel Ludger Bisseck", 77, "gold_rare", "DFC", "de"),
        ("Arnautovic", "Marko Arnautović", 77, "gold_rare", "DEL", "at"),
        ("Josep Martinez", "Josep Martínez Riera", 76, "gold_rare", "POR", "es"),
    ],
    "Bayer Leverkusen": [
        ("Wirtz", "Florian Richard Wirtz", 88, "gold_rare", "MCO", "de"),
        ("Xhaka", "Granit Xhaka", 86, "gold_rare", "MCD", "ch"),
        ("Grimaldo", "Alejandro Grimaldo García", 86, "gold_rare", "LI", "es"),
        ("Frimpong", "Jeremie Agyekum Frimpong", 86, "gold_rare", "LD", "nl"),
        ("Tah", "Jonathan Glao Tah", 86, "gold_rare", "DFC", "de"),
        ("Palacios", "Exequiel Alejandro Palacios", 84, "gold_rare", "MC", "ar"),
        ("Boniface", "Victor Okoh Boniface", 82, "gold_rare", "DEL", "ng"),
        ("Schick", "Patrik Schick", 82, "gold_rare", "DEL", "cz"),
        ("Tapsoba", "Edmond Fayçal Tapsoba", 82, "gold_rare", "DFC", "bf"),
        ("Hincapie", "Piero Martín Hincapié Reyna", 81, "gold_rare", "DFC", "ec"),
        ("Hradecky", "Lukáš Hrádecký", 84, "gold_rare", "POR", "fi"),
        ("Andrich", "Robert Andrich", 82, "gold_rare", "MCD", "de"),
        ("Hofmann", "Jonas Hofmann", 81, "gold_rare", "MCO", "de"),
        ("Adli", "Amine Adli", 78, "gold_rare", "EI", "ma"),
        ("Terrier", "Martin Albert Frédéric Terrier", 80, "gold_rare", "DEL", "fr"),
        ("Aleix Garcia", "Aleix García Serrano", 82, "gold_rare", "MC", "es"),
        ("Tella", "Nathan Anthony Adewale Temitayo Tella", 78, "gold_rare", "ED", "ng"),
        ("Mukiele", "Nordi Mukiele Mulere", 78, "gold_rare", "LD", "fr"),
        ("Belocian", "Jeanuël Belocian", 72, "silver", "DFC", "fr"),
        ("Kovar", "Matěj Kovář", 75, "gold_rare", "POR", "cz"),
    ],
    "Chelsea": [
        ("Cole Palmer", "Cole Jermaine Palmer", 85, "gold_rare", "MCO", "gb-eng"),
        ("Caicedo", "Moisés Isaac Caicedo Corozo", 82, "gold_rare", "MCD", "ec"),
        ("Enzo Fernandez", "Enzo Jeremías Fernández", 82, "gold_rare", "MC", "ar"),
        ("Nkunku", "Christopher Alan Nkunku", 84, "gold_rare", "MCO", "fr"),
        ("Jackson", "Nicolas Jackson", 79, "gold_rare", "DEL", "sn"),
        ("Pedro Neto", "Pedro Lomba Neto", 79, "gold_rare", "ED", "pt"),
        ("Madueke", "Chukwunonso Tristan Madueke", 78, "gold_rare", "ED", "gb-eng"),
        ("Mudryk", "Mykhailo Petrovych Mudryk", 77, "gold_rare", "EI", "ua"),
        ("Sancho", "Jadon Malik Sancho", 82, "gold_rare", "EI", "gb-eng"),
        ("Felix", "João Félix Sequeira", 80, "gold_rare", "DEL", "pt"),
        ("Colwill", "Levi Lemar Samuel Colwill", 79, "gold_rare", "DFC", "gb-eng"),
        ("Fofana", "Wesley Tidjan Fofana", 78, "gold_rare", "DFC", "fr"),
        ("James", "Reece Lewis James", 82, "gold_rare", "LD", "gb-eng"),
        ("Gusto", "Malo Arthur Gusto", 79, "gold_rare", "LD", "fr"),
        ("Cucurella", "Marc Cucurella Saseta", 82, "gold_rare", "LI", "es"),
        ("Lavia", "Roméo Lavia", 76, "gold_rare", "MCD", "be"),
        ("Sanchez", "Robert Lynch Sánchez", 77, "gold_rare", "POR", "es"),
        ("Adarabioyo", "Abdul-Nasir Oluwatosin Adarabioyo", 78, "gold_rare", "DFC", "gb-eng"),
        ("Badiashile", "Benoît Nambitingue Badiashile", 77, "gold_rare", "DFC", "fr"),
        ("Disasi", "Axel Wilson Arthur Disasi Mhakote", 78, "gold_rare", "DFC", "fr"),
        ("Guiu", "Marc Guiu Paz", 69, "silver", "DEL", "es"),
    ],
    "Manchester United": [
        ("Bruno Fernandes", "Bruno Miguel Borges Fernandes", 87, "gold_rare", "MCO", "pt"),
        ("Rashford", "Marcus Rashford", 81, "gold_rare", "EI", "gb-eng"),
        ("Hojlund", "Rasmus Winther Højlund", 78, "gold_rare", "DEL", "dk"),
        ("Zirkzee", "Joshua Orobosa Zirkzee", 79, "gold_rare", "DEL", "nl"),
        ("Garnacho", "Alejandro Garnacho Ferreyra", 79, "gold_rare", "EI", "ar"),
        ("Amad", "Amad Diallo", 76, "gold_rare", "ED", "ci"),
        ("Mainoo", "Kobbie Boateng Mainoo", 77, "gold_rare", "MC", "gb-eng"),
        ("Ugarte", "Manuel Ugarte Ribeiro", 81, "gold_rare", "MCD", "uy"),
        ("Casemiro", "Carlos Henrique Casimiro", 84, "gold_rare", "MCD", "br"),
        ("Eriksen", "Christian Dannemann Eriksen", 80, "gold_rare", "MC", "dk"),
        ("Lisandro Martinez", "Lisandro Martínez", 84, "gold_rare", "DFC", "ar"),
        ("De Ligt", "Matthijs de Ligt", 84, "gold_rare", "DFC", "nl"),
        ("Maguire", "Jacob Harry Maguire", 79, "gold_rare", "DFC", "gb-eng"),
        ("Yoro", "Leny Olivier Yoro", 78, "gold_rare", "DFC", "fr"),
        ("Dalot", "José Diogo Dalot Teixeira", 82, "gold_rare", "LD", "pt"),
        ("Mazraoui", "Noussair Mazraoui", 81, "gold_rare", "LD", "ma"),
        ("Shaw", "Luke Paul Hoare Shaw", 82, "gold_rare", "LI", "gb-eng"),
        ("Malacia", "Tyrell Johannes Chicco Malacia", 76, "gold_rare", "LI", "nl"),
        ("Onana", "André Onana Onana", 83, "gold_rare", "POR", "cm"),
        ("Mount", "Mason Tony Mount", 80, "gold_rare", "MCO", "gb-eng"),
        ("Antony", "Antony Matheus dos Santos", 77, "gold_rare", "ED", "br"),
        ("Bayindir", "Altay Bayındır", 76, "gold_rare", "POR", "tr"),
    ],
    "Atlético de Madrid": [
        ("Griezmann", "Antoine Griezmann", 88, "gold_rare", "DEL", "fr"),
        ("Julian Alvarez", "Julián Álvarez", 84, "gold_rare", "DEL", "ar"),
        ("Oblak", "Jan Oblak", 88, "gold_rare", "POR", "si"),
        ("Sorloth", "Alexander Sørloth", 82, "gold_rare", "DEL", "no"),
        ("Koke", "Jorge Resurrección Merodio", 83, "gold_rare", "MC", "es"),
        ("De Paul", "Rodrigo Javier De Paul", 84, "gold_rare", "MC", "ar"),
        ("Gallagher", "Conor John Gallagher", 81, "gold_rare", "MC", "gb-eng"),
        ("Llorente", "Marcos Llorente Moreno", 83, "gold_rare", "LD", "es"),
        ("Gimenez", "José María Giménez de Vargas", 83, "gold_rare", "DFC", "uy"),
        ("Le Normand", "Robin Aime Robert Le Normand", 83, "gold_rare", "DFC", "es"),
        ("Witsel", "Axel Laurent Angel Lambert Witsel", 81, "gold_rare", "DFC", "be"),
        ("Reinildo", "Reinildo Isnard Mandava", 79, "gold_rare", "LI", "mz"),
        ("Molina", "Nahuel Molina Lucero", 80, "gold_rare", "LD", "ar"),
        ("Lino", "Samuel Dias Lino", 81, "gold_rare", "LI", "br"),
        ("Riquelme", "Rodrigo Riquelme Reche", 78, "gold_rare", "MI", "es"),
        ("Correa", "Ángel Martín Correa Martínez", 81, "gold_rare", "DEL", "ar"),
        ("Barrios", "Pablo Barrios Rivas", 77, "gold_rare", "MC", "es"),
        ("Musso", "Juan Agustín Musso", 78, "gold_rare", "POR", "ar"),
        ("Lenglet", "Clément Nicolas Laurent Lenglet", 77, "gold_rare", "DFC", "fr"),
        ("Azpilicueta", "César Azpilicueta Tanco", 79, "gold_rare", "DFC", "es"),
    ],
    "Juventus": [
        ("Vlahovic", "Dušan Vlahović", 84, "gold_rare", "DEL", "rs"),
        ("Koopmeiners", "Teun Koopmeiners", 83, "gold_rare", "MC", "nl"),
        ("Bremer", "Gleison Bremer Silva Nascimento", 86, "gold_rare", "DFC", "br"),
        ("Di Gregorio", "Michele Di Gregorio", 82, "gold_rare", "POR", "it"),
        ("Douglas Luiz", "Douglas Luiz Soares de Paulo", 83, "gold_rare", "MC", "br"),
        ("Thuram Jr", "Khéphren Thuram-Ulien", 79, "gold_rare", "MC", "fr"),
        ("Locatelli", "Manuel Locatelli", 81, "gold_rare", "MCD", "it"),
        ("Nico Gonzalez", "Nicolás Iván González", 81, "gold_rare", "ED", "ar"),
        ("Conceicao", "Rodrigo Fernandes da Conceição", 78, "gold_rare", "ED", "pt"),
        ("Yildiz", "Kenan Yıldız", 74, "silver", "EI", "tr"),
        ("Cambiaso", "Andrea Cambiaso", 79, "gold_rare", "LI", "it"),
        ("Gatti", "Federico Gatti", 79, "gold_rare", "DFC", "it"),
        ("Kalulu", "Pierre Kazeye Rommel Kalulu Kyatengwa", 78, "gold_rare", "DFC", "fr"),
        ("Danilo", "Danilo Luiz da Silva", 81, "gold_rare", "DFC", "br"),
        ("Fagioli", "Nicolò Fagioli", 77, "gold_rare", "MC", "it"),
        ("Milik", "Arkadiusz Krystian Milik", 78, "gold_rare", "DEL", "pl"),
        ("Weah", "Timothy Tarpeh Weah", 76, "gold_rare", "ED", "us"),
        ("McKennie", "Weston James Earl McKennie", 78, "gold_rare", "MC", "us"),
        ("Perin", "Mattia Perin", 78, "gold_rare", "POR", "it"),
        ("Cabal", "Juan David Cabal Murillo", 74, "silver", "LI", "co"),
    ],
    "AC Milan": [
        ("Leao", "Rafael Alexandre da Conceição Leão", 86, "gold_rare", "EI", "pt"),
        ("Maignan", "Mike Peterson Maignan", 87, "gold_rare", "POR", "fr"),
        ("Theo Hernandez", "Theo Bernard François Hernández", 87, "gold_rare", "LI", "fr"),
        ("Pulisic", "Christian Mate Pulisic", 83, "gold_rare", "ED", "us"),
        ("Morata", "Álvaro Borja Morata Martín", 83, "gold_rare", "DEL", "es"),
        ("Reijnders", "Tijjani Martinus Jan Reijnders", 82, "gold_rare", "MC", "nl"),
        ("Tomori", "Oluwafikayomi Oluwadamilola Tomori", 83, "gold_rare", "DFC", "gb-eng"),
        ("Pavlovic", "Strahinja Pavlović", 78, "gold_rare", "DFC", "rs"),
        ("Fofana", "Youssouf Fofana", 81, "gold_rare", "MCD", "fr"),
        ("Loftus-Cheek", "Ruben Ira Loftus-Cheek", 80, "gold_rare", "MC", "gb-eng"),
        ("Chukwueze", "Samuel Chimerenka Chukwueze", 79, "gold_rare", "ED", "ng"),
        ("Okafor", "Noah Arinzechukwu Okafor", 77, "gold_rare", "DEL", "ch"),
        ("Emerson Royal", "Emerson Aparecido Leite de Souza Junior", 78, "gold_rare", "LD", "br"),
        ("Calabria", "Davide Calabria", 80, "gold_rare", "LD", "it"),
        ("Thiaw", "Malick Laye Thiaw", 78, "gold_rare", "DFC", "de"),
        ("Gabbia", "Matteo Gabbia", 77, "gold_rare", "DFC", "it"),
        ("Musah", "Yunus Dimoara Musah", 76, "gold_rare", "MC", "us"),
        ("Abraham", "Tammy Bakumo-Abraham", 77, "gold_rare", "DEL", "gb-eng"),
        ("Sportiello", "Marco Sportiello", 76, "gold_rare", "POR", "it"),
        ("Camarda", "Francesco Camarda", 65, "bronze", "DEL", "it"),
    ],
    "Borussia Dortmund": [
        ("Kobel", "Gregor Kobel", 88, "gold_rare", "POR", "ch"),
        ("Brandt", "Julian Brandt", 85, "gold_rare", "MCO", "de"),
        ("Schlotterbeck", "Nico Schlotterbeck", 85, "gold_rare", "DFC", "de"),
        ("Guirassy", "Serhou Yadaly Guirassy", 82, "gold_rare", "DEL", "gn"),
        ("Malen", "Donyell Malen", 81, "gold_rare", "ED", "nl"),
        ("Adeyemi", "Karim-David Adeyemi", 80, "gold_rare", "EI", "de"),
        ("Sabitzer", "Marcel Sabitzer", 82, "gold_rare", "MC", "at"),
        ("Can", "Emre Can", 82, "gold_rare", "MCD", "de"),
        ("Gross", "Pascal Groß", 81, "gold_rare", "MC", "de"),
        ("Gittens", "Jamie Jermaine Bynoe-Gittens", 76, "gold_rare", "EI", "gb-eng"),
        ("Anton", "Waldemar Anton", 82, "gold_rare", "DFC", "de"),
        ("Sule", "Niklas Süle", 81, "gold_rare", "DFC", "de"),
        ("Ryerson", "Julian Ryerson", 79, "gold_rare", "LD", "no"),
        ("Bensebaini", "Ramy Bensebaini", 78, "gold_rare", "LI", "dz"),
        ("Couto", "Yan Bueno Couto", 77, "gold_rare", "LD", "br"),
        ("Nmecha", "Felix Kalu Nmecha", 76, "gold_rare", "MC", "de"),
        ("Beier", "Maximilian Beier", 78, "gold_rare", "DEL", "de"),
        ("Reyna", "Giovanni Alejandro Reyna", 76, "gold_rare", "MCO", "us"),
        ("Meyer", "Alexander Meyer-Schade", 74, "silver", "POR", "de"),
        ("Duranville", "Julien Duranville", 68, "silver", "ED", "be"),
    ],
    "Tottenham Hotspur": [
        ("Son", "Son Heung-min", 87, "gold_rare", "EI", "kr"),
        ("Romero", "Cristian Gabriel Romero", 84, "gold_rare", "DFC", "ar"),
        ("Van de Ven", "Micky van de Ven", 82, "gold_rare", "DFC", "nl"),
        ("Vicario", "Guglielmo Vicario", 84, "gold_rare", "POR", "it"),
        ("Maddison", "James Daniel Maddison", 85, "gold_rare", "MCO", "gb-eng"),
        ("Kulusevski", "Dejan Kulusevski", 82, "gold_rare", "ED", "se"),
        ("Solanke", "Dominic Ayodele Solanke-Mitchell", 81, "gold_rare", "DEL", "gb-eng"),
        ("Porro", "Pedro Antonio Porro Sauceda", 83, "gold_rare", "LD", "es"),
        ("Udogie", "Iyenoma Destiny Udogie", 82, "gold_rare", "LI", "it"),
        ("Sarr", "Pape Matar Sarr", 78, "gold_rare", "MC", "sn"),
        ("Bissouma", "Yves Bissouma", 81, "gold_rare", "MCD", "ml"),
        ("Bentancur", "Rodrigo Bentancur Colmán", 81, "gold_rare", "MC", "uy"),
        ("Richarlison", "Richarlison de Andrade", 80, "gold_rare", "DEL", "br"),
        ("Johnson", "Brennan Price Johnson", 77, "gold_rare", "ED", "gb-wls"),
        ("Odobert", "Wilson Odobert", 74, "silver", "EI", "fr"),
        ("Dragusin", "Radu Matei Drăgușin", 76, "gold_rare", "DFC", "ro"),
        ("Bergvall", "Lucas Erik Holger Bergvall", 71, "silver", "MC", "se"),
        ("Gray", "Archie James Francis Gray", 73, "silver", "MCD", "gb-eng"),
        ("Davies", "Benjamin Thomas Davies", 77, "gold_rare", "DFC", "gb-wls"),
        ("Forster", "Fraser Gerard Forster", 73, "silver", "POR", "gb-eng"),
    ],
    "Roma": [
        ("Dybala", "Paulo Exequiel Dybala", 87, "gold_rare", "DEL", "ar"),
        ("Pellegrini", "Lorenzo Pellegrini", 83, "gold_rare", "MCO", "it"),
        ("Mancini", "Gianluca Mancini", 83, "gold_rare", "DFC", "it"),
        ("Ndicka", "Obite Evan Ndicka", 81, "gold_rare", "DFC", "ci"),
        ("Svilar", "Mile Svilar", 80, "gold_rare", "POR", "rs"),
        ("Dovbyk", "Artem Oleksandrovych Dovbyk", 84, "gold_rare", "DEL", "ua"),
        ("Soule", "Matías Soulé Malvano", 78, "gold_rare", "ED", "ar"),
        ("Kone", "Emmanuel Kouadio Koné", 79, "gold_rare", "MC", "fr"),
        ("Cristante", "Bryan Cristante", 80, "gold_rare", "MCD", "it"),
        ("Paredes", "Leandro Daniel Paredes", 81, "gold_rare", "MCD", "ar"),
        ("El Shaarawy", "Stephan Kareem El Shaarawy", 78, "gold_rare", "EI", "it"),
        ("Angelino", "José Ángel Esmorís Tasende", 79, "gold_rare", "LI", "es"),
        ("Saelemaekers", "Alexis Jesse Saelemaekers", 78, "gold_rare", "ED", "be"),
        ("Celik", "Mehmet Zeki Çelik", 76, "gold_rare", "LD", "tr"),
        ("Hummels", "Mats Julian Hummels", 84, "gold_rare", "DFC", "de"),
        ("Hermoso", "Mario Hermoso Canseco", 81, "gold_rare", "DFC", "es"),
        ("Baldanzi", "Tommaso Baldanzi", 75, "gold_rare", "MCO", "it"),
        ("Le Fee", "Enzo Jérémy Le Fée", 78, "gold_rare", "MC", "fr"),
        ("Zalewski", "Nicola Zalewski", 75, "gold_rare", "LI", "pl"),
        ("Ryan", "Mathew David Ryan", 77, "gold_rare", "POR", "au"),
    ],
    "Napoli": [
        ("Kvaratskhelia", "Khvicha Kvaratskhelia", 87, "gold_rare", "EI", "ge"),
        ("Lukaku", "Romelu Menama Lukaku Bolingoli", 82, "gold_rare", "DEL", "be"),
        ("Di Lorenzo", "Giovanni Di Lorenzo", 82, "gold_rare", "LD", "it"),
        ("Lobotska", "Stanislav Lobotka", 83, "gold_rare", "MC", "sk"),
        ("Anguissa", "André-Frank Zambo Anguissa", 82, "gold_rare", "MC", "cm"),
        ("Buongiorno", "Alessandro Buongiorno", 81, "gold_rare", "DFC", "it"),
        ("Rrahmani", "Amir Kadri Rrahmani", 81, "gold_rare", "DFC", "xk"),
        ("Meret", "Alex Meret", 80, "gold_rare", "POR", "it"),
        ("McTominay", "Scott Francis McTominay", 79, "gold_rare", "MC", "gb-eng"),
        ("Politano", "Matteo Politano", 80, "gold_rare", "ED", "it"),
        ("Neres", "David Neres Campos", 79, "gold_rare", "ED", "br"),
        ("Olivera", "Mathías Olivera Miramontes", 78, "gold_rare", "LI", "uy"),
        ("Spinazzola", "Leonardo Spinazzola", 79, "gold_rare", "LI", "it"),
        ("Gilmour", "Billy Clifford Gilmour", 76, "gold_rare", "MC", "gb-eng"),
        ("Raspadori", "Giacomo Raspadori", 78, "gold_rare", "DEL", "it"),
        ("Simeone", "Giovanni Pablo Simeone Baldini", 76, "gold_rare", "DEL", "ar"),
        ("Mazzocchi", "Pasquale Mazzocchi", 76, "gold_rare", "LD", "it"),
        ("Caprile", "Elia Caprile", 74, "silver", "POR", "it"),
        ("Folorunsho", "Michael Ijemuan Folorunsho", 76, "gold_rare", "MC", "it"),
        ("Juan Jesus", "Juan Guilherme Nunes Jesus", 76, "gold_rare", "DFC", "br"),
    ],
    "Newcastle United": [
        ("Isak", "Alexander Isak", 85, "gold_rare", "DEL", "se"),
        ("Bruno Guimaraes", "Bruno Guimarães Rodriguez Moura", 85, "gold_rare", "MC", "br"),
        ("Gordon", "Anthony Michael Gordon", 81, "gold_rare", "EI", "gb-eng"),
        ("Tonali", "Sandro Tonali", 85, "gold_rare", "MCD", "it"),
        ("Joelinton", "Joelinton Cássio Apolinário de Lira", 82, "gold_rare", "MC", "br"),
        ("Schar", "Fabian Lukas Schär", 82, "gold_rare", "DFC", "ch"),
        ("Botman", "Sven Botman", 80, "gold_rare", "DFC", "nl"),
        ("Trippier", "Kieran John Trippier", 83, "gold_rare", "LD", "gb-eng"),
        ("Livramento", "Tino Valentino Livramento", 77, "gold_rare", "LD", "gb-eng"),
        ("Hall", "Lewis Hall", 75, "gold_rare", "LI", "gb-eng"),
        ("Burn", "Daniel Johnson Burn", 79, "gold_rare", "DFC", "gb-eng"),
        ("Pope", "Nicholas David Pope", 82, "gold_rare", "POR", "gb-eng"),
        ("Barnes", "Harvey Lewis Barnes", 80, "gold_rare", "EI", "gb-eng"),
        ("Wilson", "Callum Eddie Graham Wilson", 80, "gold_rare", "DEL", "gb-eng"),
        ("Murphy", "Jacob Kai Murphy", 76, "gold_rare", "ED", "gb-eng"),
        ("Almiron", "Miguel Ángel Almirón Rejala", 79, "gold_rare", "ED", "py"),
        ("Willock", "Joseph George Willock", 77, "gold_rare", "MC", "gb-eng"),
        ("Longstaff", "Sean David Longstaff", 77, "gold_rare", "MC", "gb-eng"),
        ("Kelly", "Lloyd Casius Kelly", 76, "gold_rare", "DFC", "gb-eng"),
        ("Dubravka", "Martin Dúbravka", 78, "gold_rare", "POR", "sk"),
    ],
    "Inter Miami": [
        ("Messi", "Lionel Andrés Messi Cuccittini", 88, "gold_rare", "ED", "ar"),
        ("Suarez", "Luis Alberto Suárez Díaz", 82, "gold_rare", "DEL", "uy"),
        ("Busquets", "Sergio Busquets Burgos", 81, "gold_rare", "MCD", "es"),
        ("Jordi Alba", "Jordi Alba Ramos", 80, "gold_rare", "LI", "es"),
        ("Campana", "Leonardo Campana Romero", 74, "silver", "DEL", "ec"),
        ("Taylor", "Robert Thomas Taylor", 73, "silver", "MI", "fi"),
        ("Callender", "Drake Steven Callender", 73, "silver", "POR", "us"),
        ("Aviles", "Tomás Agustín Avilés Mancilla", 72, "silver", "DFC", "ar"),
        ("Rojas", "Matías Nicolás Rojas Romero", 75, "gold_rare", "MCO", "py"),
        ("Redondo", "Federico Redondo Solari", 74, "silver", "MCD", "ar"),
        ("Gomez", "Diego Alexander Gómez Amarilla", 73, "silver", "MC", "py"),
        ("Cremaschi", "Benjamin Cremaschi", 70, "silver", "MC", "us"),
        ("Weigandt", "Marcelo Alexis Weigandt", 72, "silver", "LD", "ar"),
        ("Martinez", "David Héctor Martínez", 73, "silver", "DFC", "py"),
        ("Fray", "Ian Charles Michael Fray", 66, "silver", "DFC", "us"),
    ],
    "Al Nassr": [
        ("Cristiano Ronaldo", "Cristiano Ronaldo dos Santos Aveiro", 86, "gold_rare", "DEL", "pt"),
        ("Mane", "Sadio Mané", 84, "gold_rare", "EI", "sn"),
        ("Laporte", "Aymeric Jean Louis Gérard Alphonse Laporte", 83, "gold_rare", "DFC", "es"),
        ("Brozovic", "Marcelo Brozović", 83, "gold_rare", "MCD", "hr"),
        ("Otavio", "Otávio Edmilson da Silva Monteiro", 82, "gold_rare", "MCO", "pt"),
        ("Simakan", "Mohamed Simakan", 80, "gold_rare", "DFC", "fr"),
        ("Bento", "Bento Matheus Krepski", 80, "gold_rare", "POR", "br"),
        ("Angelo", "Ângelo Gabriel Borges Damaceno", 76, "gold_rare", "ED", "br"),
        ("Talisca", "Anderson Souza Conceição", 81, "gold_rare", "MCO", "br"),
        ("Al Ghannam", "Sultan Abdullah Al-Ghannam", 74, "silver", "LD", "sa"),
        ("Al Khaibari", "Abdullah Al-Khaibari", 72, "silver", "MCD", "sa"),
        ("Lajami", "Ali Lajami", 73, "silver", "DFC", "sa"),
        ("Ghareeb", "Abdulrahman Ghareeb", 74, "silver", "EI", "sa"),
        ("Al Najjar", "Raghid Al-Najjar", 66, "silver", "POR", "sa"),
    ],
    "Al Hilal": [
        ("Neymar Jr", "Neymar da Silva Santos Júnior", 87, "gold_rare", "EI", "br"),
        ("Mitrovic", "Aleksandar Mitrović", 82, "gold_rare", "DEL", "rs"),
        ("Milinkovic-Savic", "Sergej Milinković-Savić", 85, "gold_rare", "MC", "rs"),
        ("Neves", "Rúben Diogo da Silva Neves", 84, "gold_rare", "MC", "pt"),
        ("Cancelo", "João Pedro Cavaco Cancelo", 84, "gold_rare", "LD", "pt"),
        ("Malcom", "Malcom Filipe Silva de Oliveira", 82, "gold_rare", "ED", "br"),
        ("Koulibaly", "Kalidou Koulibaly", 84, "gold_rare", "DFC", "sn"),
        ("Bono", "Yassine Bounou", 84, "gold_rare", "POR", "ma"),
        ("Lodi", "Renan Augusto Lodi dos Santos", 79, "gold_rare", "LI", "br"),
        ("Al Dawsari", "Salem Muwaffaq Al-Dawsari", 78, "gold_rare", "EI", "sa"),
        ("Al Bulayhi", "Ali Al-Bulayhi", 74, "silver", "DFC", "sa"),
        ("Kanno", "Mohamed Kanno", 74, "silver", "MC", "sa"),
        ("Al Shahrani", "Yasser Al-Shahrani", 74, "silver", "LI", "sa"),
        ("Al Qahtani", "Mohammed Al-Qahtani", 67, "silver", "ED", "sa"),
    ],
    "Al Ittihad": [
        ("Benzema", "Karim Mostafa Benzema", 86, "gold_rare", "DEL", "fr"),
        ("Kante", "N'Golo Kanté", 85, "gold_rare", "MCD", "fr"),
        ("Fabinho", "Fábio Henrique Tavares", 82, "gold_rare", "MCD", "br"),
        ("Aouar", "Houssem-Eddine Chaâbane Aouar", 79, "gold_rare", "MC", "dz"),
        ("Diaby", "Moussa Diaby", 82, "gold_rare", "ED", "fr"),
        ("Bergwijn", "Steven Charles Bergwijn", 79, "gold_rare", "EI", "nl"),
        ("Danilo Pereira", "Danilo Luís Hélio Pereira", 80, "gold_rare", "DFC", "pt"),
        ("Rajkovic", "Predrag Rajković", 80, "gold_rare", "POR", "rs"),
        ("Luiz Felipe", "Luiz Felipe Ramos Marchi", 78, "gold_rare", "DFC", "it"),
        ("Al Shanqeeti", "Muhannad Al-Shanqeeti", 72, "silver", "LD", "sa"),
        ("Kadesh", "Hassan Kadesh", 71, "silver", "LI", "sa"),
        ("Al Ghamdi", "Faisal Al-Ghamdi", 70, "silver", "MC", "sa"),
        ("Al Shehri", "Saleh Al-Shehri", 73, "silver", "DEL", "sa"),
    ],
    "River Plate": [
        ("Mastantuono", "Franco Mastantuono", 74, "silver", "MCO", "ar"),
        ("Borja", "Miguel Ángel Borja Hernández", 78, "gold_rare", "DEL", "co"),
        ("Armani", "Franco Armani", 77, "gold_rare", "POR", "ar"),
        ("Pezzella", "Germán Alejo Pezzella", 79, "gold_rare", "DFC", "ar"),
        ("Acuña", "Marcos Javier Acuña", 80, "gold_rare", "LI", "ar"),
        ("Lanzini", "Manuel Lanzini", 76, "gold_rare", "MCO", "ar"),
        ("Kranevitter", "Claudio Matías Kranevitter", 74, "silver", "MCD", "ar"),
        ("Meza", "Maximiliano Eduardo Meza", 77, "gold_rare", "ED", "ar"),
        ("Colidio", "Facundo Colidio", 75, "gold_rare", "DEL", "ar"),
        ("Villagra", "Rodrigo Román Villagra", 74, "silver", "MCD", "ar"),
        ("Simon", "Santiago Simón", 73, "silver", "MC", "ar"),
        ("Diaz", "Paulo César Díaz Huincales", 76, "gold_rare", "DFC", "cl"),
        ("Bustos", "Fabricio Fabricio Bustos", 76, "gold_rare", "LD", "ar"),
        ("Enzo Diaz", "Enzo Hernán Díaz", 75, "gold_rare", "LI", "ar"),
        ("Bareiro", "Adam Fernando Bareiro Gamarra", 75, "gold_rare", "DEL", "py"),
        ("Aliendro", "Rodrigo Germán Aliendro", 75, "gold_rare", "MC", "ar"),
        ("Echeverri", "Claudio Jeremías Echeverri", 75, "gold_rare", "MCO", "ar"),
        ("Ruberto", "Agustín Fabián Ruberto", 67, "silver", "DEL", "ar"),
    ],
    "Boca Juniors": [
        ("Cavani", "Edinson Roberto Cavani Gómez", 79, "gold_rare", "DEL", "uy"),
        ("Merentiel", "Miguel Ángel Merentiel Serrano", 77, "gold_rare", "DEL", "uy"),
        ("Zenon", "Kevin Andrés Zenón", 76, "gold_rare", "MI", "ar"),
        ("Medina", "Cristian Nicolás Medina", 76, "gold_rare", "MC", "ar"),
        ("Romero", "Sergio Germán Romero", 76, "gold_rare", "POR", "ar"),
        ("Rojo", "Faustino Marcos Alberto Rojo", 76, "gold_rare", "DFC", "ar"),
        ("Blanco", "Lautaro Emanuel Blanco", 76, "gold_rare", "LI", "ar"),
        ("Advincula", "Luis Jan Piers Advíncula Castrillón", 75, "gold_rare", "LD", "pe"),
        ("Gimenez", "Milton Giménez", 74, "silver", "DEL", "ar"),
        ("Zeballos", "Exequiel Zeballos", 74, "silver", "EI", "ar"),
        ("Lema", "Cristian Franco Lema", 75, "gold_rare", "DFC", "ar"),
        ("Figal", "Jorge Nicolás Figal", 74, "silver", "DFC", "ar"),
        ("Pol Fernandez", "Guillermo Matías Fernández", 75, "gold_rare", "MC", "ar"),
        ("Belmonte", "Tomás Belmonte", 74, "silver", "MCD", "ar"),
        ("Saracchi", "Marcelo Josemir Saracchi Pintos", 73, "silver", "LI", "uy"),
        ("Brey", "Leandro Brey", 69, "silver", "POR", "ar"),
    ],
    "Palmeiras": [
        ("Estevao", "Estêvão Willian Almeida de Oliveira Gonçalves", 74, "silver", "ED", "br"),
        ("Veiga", "Raphael Cavalcante Veiga", 80, "gold_rare", "MCO", "br"),
        ("Gomez", "Gustavo Raúl Gómez Portillo", 81, "gold_rare", "DFC", "py"),
        ("Weverton", "Weverton Pereira da Silva", 80, "gold_rare", "POR", "br"),
        ("Murilo", "Murilo Cerqueira Paim", 78, "gold_rare", "DFC", "br"),
        ("Piquerez", "Joaquín Piquerez Moreira", 79, "gold_rare", "LI", "uy"),
        ("Mayke", "Mayke Rocha Oliveira", 76, "gold_rare", "LD", "br"),
        ("Ze Rafael", "José Rafael Vivian", 78, "gold_rare", "MC", "br"),
        ("Rios", "Richard Ríos Montoya", 77, "gold_rare", "MC", "co"),
        ("Anibal Moreno", "Aníbal Ismael Moreno", 77, "gold_rare", "MCD", "ar"),
        ("Rony", "Ronielson da Silva Barbosa", 76, "gold_rare", "DEL", "br"),
        ("Flaco Lopez", "José Manuel Alberto López", 75, "gold_rare", "DEL", "ar"),
        ("Dudu", "Eduardo Pereira Rodrigues", 78, "gold_rare", "EI", "br"),
        ("Mauricio", "Maurício Magalhães Prado", 75, "gold_rare", "MCO", "br"),
        ("Giay", "Agustín Giay", 73, "silver", "LD", "ar"),
        ("Gabriel Menino", "Gabriel Vinicius Menino Aquino", 74, "silver", "MC", "br"),
    ],
    "Como": [
        ("Nico Paz", "Nicolás Paz Martínez", 74, "silver", "MCO", "ar"),
        ("Cutrone", "Patrick Cutrone", 75, "gold_rare", "DEL", "it"),
        ("Belotti", "Andrea Belotti", 76, "gold_rare", "DEL", "it"),
        ("Strefezza", "Gabriel Barbosa Strefezza", 76, "gold_rare", "ED", "br"),
        ("Sergi Roberto", "Sergi Roberto Carnicer", 77, "gold_rare", "MC", "es"),
        ("Fadera", "Alieu Fadera", 72, "silver", "EI", "gm"),
        ("Perrone", "Máximo Perrone", 74, "silver", "MCD", "ar"),
        ("Audero", "Emil Audero Mulyadi", 76, "gold_rare", "POR", "it"),
        ("Dossena", "Alberto Dossena", 75, "gold_rare", "DFC", "it"),
        ("Kempf", "Marc-Oliver Kempf", 75, "gold_rare", "DFC", "de"),
        ("Moreno", "Alberto Moreno Pérez", 76, "gold_rare", "LI", "es"),
        ("Van Der Brempt", "Ignace Van Der Brempt", 72, "silver", "LD", "be"),
        ("Da Cunha", "Lucas Da Cunha", 73, "silver", "MC", "fr"),
        ("Mazzitelli", "Luca Mazzitelli", 74, "silver", "MC", "it"),
        ("Goldaniga", "Edoardo Goldaniga", 73, "silver", "DFC", "it"),
        ("Reina", "José Manuel Reina Páez", 73, "silver", "POR", "es"),
    ]
}

# Más clubes con sus principales figuras para asegurar más de 1000 jugadores
MORE_CLUBS = {
    "Sporting CP": [
        ("Gyokeres", "Viktor Einar Gyökeres", 85, "gold_rare", "DEL", "se"),
        ("Hjulmand", "Morten Blom Due Hjulmand", 82, "gold_rare", "MCD", "dk"),
        ("Inacio", "Gonçalo Bernardo Inácio", 81, "gold_rare", "DFC", "pt"),
        ("Diomande", "Ousmane Diomande", 79, "gold_rare", "DFC", "ci"),
        ("Trincao", "Francisco António Machado Mota Castro Trincão", 80, "gold_rare", "ED", "pt"),
        ("Pote", "Pedro António Pereira Gonçalves", 83, "gold_rare", "MCO", "pt"),
        ("Catamo", "Geny Cipriano Catamo", 77, "gold_rare", "LD", "mz"),
        ("Morita", "Hidemasa Morita", 80, "gold_rare", "MC", "jp"),
        ("Quenda", "Geovany Quenda", 72, "silver", "ED", "pt"),
        ("Israel", "Franco Israel Wibmer", 75, "gold_rare", "POR", "uy"),
    ],
    "Porto": [
        ("Diogo Costa", "Diogo Meireles da Costa", 84, "gold_rare", "POR", "pt"),
        ("Galeno", "Wenderson Rodrigues do Carmo Galeno", 81, "gold_rare", "EI", "br"),
        ("Samu Omorodion", "Samuel Omorodion Aghehowa", 77, "gold_rare", "DEL", "es"),
        ("Varela", "Alan Gonzalo Varela", 80, "gold_rare", "MCD", "ar"),
        ("Pepe", "Eduardo Gabriel Aquino Cossa", 81, "gold_rare", "ED", "br"),
        ("Nico Gonzalez", "Nicolás González Iglesias", 78, "gold_rare", "MC", "es"),
        ("Otavio", "Otávio Paulo Neves Santos", 77, "gold_rare", "DFC", "br"),
        ("Joao Mario", "João Mário Neto Lopes", 79, "gold_rare", "LD", "pt"),
        ("Fabio Vieira", "Fábio Daniel Ferreira Vieira", 78, "gold_rare", "MCO", "pt"),
        ("Danny Namaso", "Daniel Namaso Loader", 73, "silver", "DEL", "gb-eng"),
    ],
    "Ajax": [
        ("Brobbey", "Brian Ebenezer Adjei Brobbey", 79, "gold_rare", "DEL", "nl"),
        ("Berghuis", "Steven Berghuis", 80, "gold_rare", "ED", "nl"),
        ("Taylor", "Kenneth Ina Dorothea Taylor", 77, "gold_rare", "MC", "nl"),
        ("Hato", "Jorrel Hato", 76, "gold_rare", "DFC", "nl"),
        ("Pasveer", "Remko Pasveer", 76, "gold_rare", "POR", "nl"),
        ("Henderson", "Jordan Brian Henderson", 79, "gold_rare", "MCD", "gb-eng"),
        ("Godts", "Mika Godts", 71, "silver", "EI", "be"),
        ("Traore", "Bertrand Isidore Traoré", 77, "gold_rare", "ED", "bf"),
        ("Sutalo", "Josip Šutalo", 78, "gold_rare", "DFC", "hr"),
        ("Rensch", "Devyne Fabian Jairo Rensch", 76, "gold_rare", "LD", "nl"),
    ],
    "PSV": [
        ("De Jong", "Luuk de Jong", 81, "gold_rare", "DEL", "nl"),
        ("Bakayoko", "Saint-Cyr Johan Bakayoko", 80, "gold_rare", "ED", "be"),
        ("Veerman", "Joey Veerman", 81, "gold_rare", "MC", "nl"),
        ("Schouten", "Jerdy Schouten", 81, "gold_rare", "MCD", "nl"),
        ("Lang", "Noa Noëll Lang", 78, "gold_rare", "EI", "nl"),
        ("Til", "Guus Til", 78, "gold_rare", "MCO", "nl"),
        ("Dest", "Sergiño Gianni Dest", 79, "gold_rare", "LI", "us"),
        ("Boscagli", "Olivier Boscagli", 80, "gold_rare", "DFC", "fr"),
        ("Flamingo", "Ryan Flamingo", 74, "silver", "DFC", "nl"),
        ("Benitez", "Walter Daniel Benítez", 81, "gold_rare", "POR", "ar"),
    ],
    "Galatasaray": [
        ("Icardi", "Mauro Emanuel Icardi", 83, "gold_rare", "DEL", "ar"),
        ("Osimhen", "Victor James Osimhen", 87, "gold_rare", "DEL", "ng"),
        ("Torreira", "Lucas Sebastián Torreira Di Pascua", 82, "gold_rare", "MCD", "uy"),
        ("Muslera", "Néstor Fernando Muslera Micol", 81, "gold_rare", "POR", "uy"),
        ("Davinson Sanchez", "Dávinson Sánchez Mina", 80, "gold_rare", "DFC", "co"),
        ("Sara", "Gabriel Davi Gomes Sara", 78, "gold_rare", "MC", "br"),
        ("Mertens", "Dries Mertens", 81, "gold_rare", "MCO", "be"),
        ("Ziyech", "Hakim Ziyech", 80, "gold_rare", "ED", "ma"),
        ("Baris Alper Yilmaz", "Barış Alper Yılmaz", 77, "gold_rare", "ED", "tr"),
        ("Nelsson", "Victor Enok Nelsson", 78, "gold_rare", "DFC", "dk"),
        ("Jakobs", "Ismail Joshua Jakobs", 75, "gold_rare", "LI", "sn"),
        ("Batshuayi", "Michy Batshuayi Tunga", 77, "gold_rare", "DEL", "be"),
    ],
    "Fenerbahce": [
        ("Dzeko", "Edin Džeko", 82, "gold_rare", "DEL", "ba"),
        ("Tadic", "Dušan Tadić", 82, "gold_rare", "EI", "rs"),
        ("Fred", "Frederico Rodrigues de Paula Santos", 81, "gold_rare", "MC", "br"),
        ("Amrabat", "Sofyan Amrabat", 81, "gold_rare", "MCD", "ma"),
        ("En-Nesyri", "Youssef En-Nesyri", 81, "gold_rare", "DEL", "ma"),
        ("Livakovic", "Dominik Livaković", 81, "gold_rare", "POR", "hr"),
        ("Szymanski", "Sebastian Szymański", 79, "gold_rare", "MCO", "pl"),
        ("Soyuncu", "Çağlar Söyüncü", 77, "gold_rare", "DFC", "tr"),
        ("Djiku", "Alexander Kwabena Baidoo Djiku", 78, "gold_rare", "DFC", "gh"),
        ("Kadioglu", "Ferdi Erenay Kadıoğlu", 80, "gold_rare", "LI", "tr"),
    ],
    "Atalanta": [
        ("Lookman", "Ademola Olajide Lookman", 83, "gold_rare", "DEL", "ng"),
        ("Retegui", "Mateo Retegui", 80, "gold_rare", "DEL", "it"),
        ("Ederson", "Éderson José dos Santos Lourenço da Silva", 82, "gold_rare", "MC", "br"),
        ("De Ketelaere", "Charles De Ketelaere", 80, "gold_rare", "MCO", "be"),
        ("Scalvini", "Giorgio Scalvini", 78, "gold_rare", "DFC", "it"),
        ("Hien", "Isak Malcolm Kwaku Hien", 78, "gold_rare", "DFC", "se"),
        ("Ruggeri", "Matteo Ruggeri", 77, "gold_rare", "LI", "it"),
        ("Zappacosta", "Davide Zappacosta", 78, "gold_rare", "LD", "it"),
        ("Pasalic", "Mario Pašalić", 80, "gold_rare", "MC", "hr"),
        ("Carnesecchi", "Marco Carnesecchi", 80, "gold_rare", "POR", "it"),
        ("Kolasinac", "Sead Kolašinac", 79, "gold_rare", "DFC", "ba"),
        ("Samardzic", "Lazar Samardžić", 77, "gold_rare", "MCO", "rs"),
    ],
    "Athletic Club": [
        ("Nico Williams", "Nicholas Williams Arthuer", 85, "gold_rare", "EI", "es"),
        ("Inaki Williams", "Iñaki Williams Arthuer", 82, "gold_rare", "ED", "gh"),
        ("Sancet", "Oihan Sancet Tirapu", 82, "gold_rare", "MCO", "es"),
        ("Unai Simon", "Unai Simón Mendibil", 83, "gold_rare", "POR", "es"),
        ("Vivian", "Daniel Vivian Moreno", 81, "gold_rare", "DFC", "es"),
        ("Yeray", "Yeray Álvarez López", 80, "gold_rare", "DFC", "es"),
        ("Yuri", "Yuri Berchiche Izeta", 80, "gold_rare", "LI", "es"),
        ("De Marcos", "Óscar de Marcos Arana", 79, "gold_rare", "LD", "es"),
        ("Galarreta", "Iñigo Ruiz de Galarreta Etxeberria", 79, "gold_rare", "MC", "es"),
        ("Guruzeta", "Gorka Guruzeta Rodríguez", 79, "gold_rare", "DEL", "es"),
        ("Berenguer", "Alejandro Berenguer Remiro", 78, "gold_rare", "EI", "es"),
        ("Prados", "Beñat Prados Díaz", 76, "gold_rare", "MC", "es"),
        ("Jauregizar", "Mikel Jauregizar Alboniga", 71, "silver", "MC", "es"),
        ("Agirrezabala", "Julen Agirrezabala Astúlez", 76, "gold_rare", "POR", "es"),
    ],
    "Real Sociedad": [
        ("Zubimendi", "Martín Zubimendi Ibáñez", 84, "gold_rare", "MCD", "es"),
        ("Kubo", "Takefusa Kubo", 82, "gold_rare", "ED", "jp"),
        ("Oyarzabal", "Mikel Oyarzabal Ugarte", 83, "gold_rare", "DEL", "es"),
        ("Remiro", "Álex Remiro Gargallo", 83, "gold_rare", "POR", "es"),
        ("Brais Mendez", "Brais Méndez Portela", 82, "gold_rare", "MC", "es"),
        ("Barrenetxea", "Ander Barrenetxea Muguruza", 78, "gold_rare", "EI", "es"),
        ("Sucic", "Luka Sučić", 77, "gold_rare", "MC", "hr"),
        ("Zubeldia", "Igor Zubeldia Elorza", 80, "gold_rare", "DFC", "es"),
        ("Aguerd", "Nayef Aguerd", 80, "gold_rare", "DFC", "ma"),
        ("Traore", "Hamari Traoré", 79, "gold_rare", "LD", "ml"),
        ("Javi Lopez", "Javier López Carballo", 76, "gold_rare", "LI", "es"),
        ("Sergio Gomez", "Sergio Gómez Martín", 77, "gold_rare", "LI", "es"),
        ("Oskarsson", "Orri Steinn Óskarsson", 73, "silver", "DEL", "is"),
    ],
    "Real Betis": [
        ("Isco", "Francisco Román Alarcón Suárez", 84, "gold_rare", "MCO", "es"),
        ("Lo Celso", "Giovani Lo Celso", 81, "gold_rare", "MC", "ar"),
        ("Vitor Roque", "Vitor Hugo Roque Ferreira", 76, "gold_rare", "DEL", "br"),
        ("Abde", "Abdessamad Ezzalzouli", 77, "gold_rare", "EI", "ma"),
        ("Fornals", "Pablo Fornals Malla", 78, "gold_rare", "MCO", "es"),
        ("Johnny Cardoso", "João Lucas de Souza Cardoso", 77, "gold_rare", "MCD", "us"),
        ("Marc Roca", "Marc Roca Junqué", 78, "gold_rare", "MCD", "es"),
        ("Bartra", "Marc Bartra Aregall", 77, "gold_rare", "DFC", "es"),
        ("Llorente", "Diego Javier Llorente Ríos", 79, "gold_rare", "DFC", "es"),
        ("Bellerin", "Héctor Bellerín Moruno", 78, "gold_rare", "LD", "es"),
        ("Perraud", "Romain Paul Jean-Michel Perraud", 76, "gold_rare", "LI", "fr"),
        ("Rui Silva", "Rui Tiago Dantas da Silva", 79, "gold_rare", "POR", "pt"),
        ("Chimy Avila", "Luis Ezequiel Ávila", 77, "gold_rare", "DEL", "ar"),
        ("Bakambu", "Cédric Bakambu", 76, "gold_rare", "DEL", "cd"),
        ("Assane Diao", "Assane Diao Diaoune", 73, "silver", "ED", "es"),
    ],
    "Villarreal": [
        ("Gerard Moreno", "Gerard Moreno Balagueró", 83, "gold_rare", "DEL", "es"),
        ("Baena", "Álex Baena Rodríguez", 82, "gold_rare", "MCO", "es"),
        ("Ayoze Perez", "Ayoze Pérez Gutiérrez", 81, "gold_rare", "DEL", "es"),
        ("Parejo", "Daniel Parejo Muñoz", 82, "gold_rare", "MC", "es"),
        ("Yeremy Pino", "Yeremy Jesús Pino Santos", 79, "gold_rare", "ED", "es"),
        ("Barry", "Thierno Mamadou Barry", 75, "gold_rare", "DEL", "fr"),
        ("Pepe", "Nicolas Pépé", 79, "gold_rare", "ED", "ci"),
        ("Comesana", "Santiago Comesaña Veiga", 78, "gold_rare", "MC", "es"),
        ("Gueye", "Pape Alassane Gueye", 77, "gold_rare", "MCD", "sn"),
        ("Albiol", "Raúl Albiol Tortajada", 79, "gold_rare", "DFC", "es"),
        ("Bailly", "Eric Bertrand Bailly", 76, "gold_rare", "DFC", "ci"),
        ("Logan Costa", "Logan Evans Costa", 76, "gold_rare", "DFC", "cv"),
        ("Foyth", "Juan Marcos Foyth", 79, "gold_rare", "LD", "ar"),
        ("Cardona", "Sergi Cardona Bermúdez", 76, "gold_rare", "LI", "es"),
        ("Conde", "Diego José Conde Alcolado", 76, "gold_rare", "POR", "es"),
    ],
    "Sevilla": [
        ("Lukebakio", "Dodi Lukébakio Ngandoli", 79, "gold_rare", "ED", "be"),
        ("Isaac Romero", "Isaac Romero Bernal", 76, "gold_rare", "DEL", "es"),
        ("Saul", "Saúl Ñíguez Esclápez", 79, "gold_rare", "MC", "es"),
        ("Sow", "Djibril Sow", 78, "gold_rare", "MC", "ch"),
        ("Lokonga", "Albert Sambi Lokonga", 76, "gold_rare", "MC", "be"),
        ("Gudelj", "Nemanja Gudelj", 78, "gold_rare", "DFC", "rs"),
        ("Bade", "Loïc Badé", 79, "gold_rare", "DFC", "fr"),
        ("Nyland", "Ørjan Håskjold Nyland", 77, "gold_rare", "POR", "no"),
        ("Pedrosa", "Adrià Giner Pedrosa", 76, "gold_rare", "LI", "es"),
        ("Juanlu", "Juan Luis Sánchez Velasco", 75, "gold_rare", "LD", "es"),
        ("Ejuke", "Chidera Ejuke", 76, "gold_rare", "EI", "ng"),
        ("Iheanacho", "Kelechi Promise Iheanacho", 76, "gold_rare", "DEL", "ng"),
        ("Peque", "Gerard Fernández Castellano", 74, "silver", "MCO", "es"),
        ("Carmona", "José Ángel Carmona Navarro", 74, "silver", "LD", "es"),
    ],
    "Girona": [
        ("Tsygankov", "Viktor Vitaliyovych Tsygankov", 83, "gold_rare", "ED", "ua"),
        ("Abel Ruiz", "Abel Ruiz Ortega", 76, "gold_rare", "DEL", "es"),
        ("Miovski", "Bojan Miovski", 76, "gold_rare", "DEL", "mk"),
        ("Herrera", "Yangel Clemente Herrera Ravelo", 79, "gold_rare", "MC", "ve"),
        ("Ivan Martin", "Iván Martín Núñez", 78, "gold_rare", "MC", "es"),
        ("Van de Beek", "Donny van de Beek", 76, "gold_rare", "MC", "nl"),
        ("Blind", "Daley Blind", 80, "gold_rare", "DFC", "nl"),
        ("David Lopez", "David López Silva", 79, "gold_rare", "DFC", "es"),
        ("Krejci", "Ladislav Krejčí", 78, "gold_rare", "DFC", "cz"),
        ("Arnau Martinez", "Arnau Martínez López", 77, "gold_rare", "LD", "es"),
        ("Gutierrez", "Miguel Gutiérrez Ortega", 80, "gold_rare", "LI", "es"),
        ("Gazzaniga", "Paulo Dino Gazzaniga", 79, "gold_rare", "POR", "ar"),
        ("Bryan Gil", "Bryan Gil Salvatierra", 77, "gold_rare", "EI", "es"),
        ("Asprilla", "Yáser Esneider Asprilla Martínez", 75, "gold_rare", "MCO", "co"),
        ("Portu", "Cristian Portugués Manzanera", 77, "gold_rare", "ED", "es"),
        ("Misehouy", "Gabriel Osei Misehouy", 68, "silver", "MCO", "nl"),
    ],
    "West Ham": [
        ("Bowen", "Jarrod Bowen", 83, "gold_rare", "ED", "gb-eng"),
        ("Kudus", "Mohammed Kudus", 83, "gold_rare", "MCO", "gh"),
        ("Lucas Paqueta", "Lucas Tolentino Coelho de Lima", 84, "gold_rare", "MCO", "br"),
        ("Fullkrug", "Niclas Füllkrug", 81, "gold_rare", "DEL", "de"),
        ("Soucek", "Tomáš Souček", 79, "gold_rare", "MC", "cz"),
        ("Edson Alvarez", "Edson Omar Álvarez Velázquez", 81, "gold_rare", "MCD", "mx"),
        ("Kilman", "Max Thomas Kilman", 80, "gold_rare", "DFC", "gb-eng"),
        ("Todibo", "Jean-Clair Dimitri Roger Todibo", 80, "gold_rare", "DFC", "fr"),
        ("Areola", "Alphonse Francis Areola", 81, "gold_rare", "POR", "fr"),
        ("Wan-Bissaka", "Aaron Wan-Bissaka", 80, "gold_rare", "LD", "gb-eng"),
        ("Emerson", "Emerson Palmieri dos Santos", 79, "gold_rare", "LI", "it"),
        ("Summerville", "Crysencio Jilbert Sylverio Cirro Summerville", 79, "gold_rare", "EI", "nl"),
        ("Rodriguez", "Guido Rodríguez", 80, "gold_rare", "MCD", "ar"),
        ("Antonio", "Michail Gregory Antonio", 76, "gold_rare", "DEL", "jm"),
        ("Coufal", "Vladimír Coufal", 77, "gold_rare", "LD", "cz"),
        ("Fabianski", "Łukasz Marek Fabiański", 76, "gold_rare", "POR", "pl"),
    ],
    "Marseille": [
        ("Greenwood", "Mason Will John Greenwood", 81, "gold_rare", "ED", "gb-eng"),
        ("Wahi", "Sepe Elye Wahi", 77, "gold_rare", "DEL", "fr"),
        ("Hojbjerg", "Pierre-Emile Kordt Højbjerg", 81, "gold_rare", "MCD", "dk"),
        ("Rabiot", "Adrien Rabiot-Provost", 82, "gold_rare", "MC", "fr"),
        ("Rulli", "Gerónimo Rulli", 80, "gold_rare", "POR", "ar"),
        ("Balerdi", "Leonardo Julián Balerdi Rosa", 79, "gold_rare", "DFC", "ar"),
        ("Kondogbia", "Geoffrey Edwin Kondogbia", 79, "gold_rare", "MCD", "cf"),
        ("Harit", "Amine Harit", 77, "gold_rare", "MCO", "ma"),
        ("Henrique", "Luis Henrique Tomaz de Lima", 76, "gold_rare", "EI", "br"),
        ("Brassier", "Lilian Brassier", 77, "gold_rare", "DFC", "fr"),
        ("Merlin", "Quentin Merlin", 76, "gold_rare", "LI", "fr"),
        ("Murillo", "Michael Amir Murillo Bermúdez", 75, "gold_rare", "LD", "pa"),
        ("Rongier", "Valentin Rongier", 79, "gold_rare", "MC", "fr"),
        ("Rowe", "Jonathan David Rowe", 74, "silver", "EI", "gb-eng"),
        ("Maupay", "Neal Maupay", 75, "gold_rare", "DEL", "fr"),
    ],
    "Monaco": [
        ("Golovin", "Aleksandr Sergeyevich Golovin", 81, "gold_rare", "MCO", "ru"),
        ("Zakaria", "Denis Lemi Zakaria Lako Lado", 81, "gold_rare", "MCD", "ch"),
        ("Embolo", "Breel-Donald Embolo", 78, "gold_rare", "DEL", "ch"),
        ("Balogun", "Folarin Jerry Balogun", 78, "gold_rare", "DEL", "us"),
        ("Akliouche", "Maghnes Akliouche", 77, "gold_rare", "ED", "fr"),
        ("Ben Seghir", "Eliesse Ben Seghir", 75, "gold_rare", "EI", "ma"),
        ("Camara", "Lamine Camara", 76, "gold_rare", "MC", "sn"),
        ("Kehrer", "Jan Thilo Kehrer", 78, "gold_rare", "DFC", "de"),
        ("Singo", "Wilfried Stephane Singo", 79, "gold_rare", "DFC", "ci"),
        ("Kohn", "Philipp Köhn", 77, "gold_rare", "POR", "ch"),
        ("Vanderson", "Vanderson de Oliveira Campos", 77, "gold_rare", "LD", "br"),
        ("Caio Henrique", "Caio Henrique Oliveira Silva", 80, "gold_rare", "LI", "br"),
        ("Minamino", "Takumi Minamino", 79, "gold_rare", "MCO", "jp"),
        ("Salisu", "Mohammed Salisu Abdul Karim", 77, "gold_rare", "DFC", "gh"),
        ("Ilenikhena", "George Ilenikhena", 72, "silver", "DEL", "fr"),
    ],
    "RB Leipzig": [
        ("Sesko", "Benjamin Šeško", 81, "gold_rare", "DEL", "si"),
        ("Openda", "Ikoma-Loïs Openda", 83, "gold_rare", "DEL", "be"),
        ("Xavi Simons", "Xavier Quentin Shay Simons", 83, "gold_rare", "MCO", "nl"),
        ("Orban", "Willi Thomas Orbán", 83, "gold_rare", "DFC", "hu"),
        ("Gulacsi", "Péter Gulácsi", 82, "gold_rare", "POR", "hu"),
        ("Lukeba", "Castello Junior Lukeba", 79, "gold_rare", "DFC", "fr"),
        ("Raum", "David Raum", 80, "gold_rare", "LI", "de"),
        ("Geertruida", "Lutsharel Geertruida", 80, "gold_rare", "LD", "nl"),
        ("Haidara", "Amadou Haidara", 78, "gold_rare", "MC", "ml"),
        ("Kampl", "Kevin Kampl", 78, "gold_rare", "MC", "si"),
        ("Henrichs", "Benjamin Paa Kwesi Henrichs", 78, "gold_rare", "LD", "de"),
        ("Seiwald", "Nicolas Seiwald", 76, "gold_rare", "MCD", "at"),
        ("Baumgartner", "Christoph Baumgartner", 79, "gold_rare", "MCO", "at"),
        ("Poulsen", "Yussuf Yurary Poulsen", 75, "gold_rare", "DEL", "dk"),
        ("Nusa", "Antonio Eromonsele Nordby Nusa", 75, "gold_rare", "EI", "no"),
        ("Vandevoordt", "Maarten Vandevoordt", 75, "gold_rare", "POR", "be"),
        ("Ouedraogo", "Assan Ouédraogo", 70, "silver", "MC", "de"),
    ],
    "Eintracht Frankfurt": [
        ("Marmoush", "Omar Khaled Mohamed Marmoush", 81, "gold_rare", "DEL", "eg"),
        ("Ekitike", "Hugo Ekitiké", 77, "gold_rare", "DEL", "fr"),
        ("Larsson", "Hugo Emanuel Larsson", 76, "gold_rare", "MC", "se"),
        ("Koch", "Robin Koch", 80, "gold_rare", "DFC", "de"),
        ("Trapp", "Kevin Trapp", 81, "gold_rare", "POR", "de"),
        ("Theate", "Arthur Nicolas Theate", 78, "gold_rare", "DFC", "be"),
        ("Kristensen", "Rasmus Nissen Kristensen", 77, "gold_rare", "LD", "dk"),
        ("Nkounkou", "Niels Patrick Nkounkou", 76, "gold_rare", "LI", "fr"),
        ("Skhiri", "Ellyes Joris Skhiri", 81, "gold_rare", "MCD", "tn"),
        ("Gotze", "Mario Götze", 80, "gold_rare", "MCO", "de"),
        ("Chaibi", "Farès Chaïbi", 76, "gold_rare", "MCO", "dz"),
        ("Knauff", "Ansgar Knauff", 75, "gold_rare", "ED", "de"),
        ("Tuta", "Lucas Silva Melo", 77, "gold_rare", "DFC", "br"),
        ("Dahoud", "Mahmoud Dahoud", 76, "gold_rare", "MC", "de"),
        ("Uzun", "Can Yılmaz Uzun", 72, "silver", "MCO", "tr"),
        ("Matanovic", "Igor Matanović", 73, "silver", "DEL", "hr"),
    ]
}

print("Catalog definition completed. Preparing final generator script...")
